### ISSUE TITLE
More technical documentation for the code

### ISSUE THREAD

**Issue by vukhoa30** [QASymphony/PulseRules_v9.1#8]
Hello @femdev, @qaschris,

As a Pulse engineer, I'm recently receiving issue tickets from clients when they have trouble using the sample codes. Since the codes lack of documentation at technical level (besides the brief description in README), it's really hard for me to understand, debug, troubleshoot and visualize the workflow of these code files. Therefore, I suggest that the software engineer team will research the codes and add more comments in the code for fully understanding, so that I and other engineers don't need so much time researching every time they receive a ticket. The details of documentation that I would like to add to each sample file:

1. Possible call source (from other action or from .sh file or rule)
2. Payload format and example
3. Constants and example
4. What would happen after the execution (Output)

So each sample file will look like this:
```
const PulseSDK = require('@qasymphony/pulse-sdk');
// ...

/**
 * call source: executeShell.sh
 * payload example:
 * {
 *   properties: 'example value'
 *   arrayOfItems: [ { <properties and example values> } ]
 * }
 * constants example:
 * - SCENARIO_PROJECT_ID: 84d46c6a-d39d-11e9-bb65-2a2ae2dbcce4
 * - QTEST_TOKEN: 84d46c6a-d39d-11e9-bb65-2a2ae2dbcce4
 * outputs:
 * - The unformatted items in the payload will be formatted into qTest test case
 * - The test cases then will be added to qTest project
 * - The unformatted result will be sent to the trigger "TriggerName"
 * - The Slack channel (if there is any) will notificate the result or error
 */

exports.handler = async function({ event, constants, triggers }, context, callback) {
  // TODO implement
}
```

Besides that, I would like to add more console.log() for better debugging.
Please review this implementation. 
Thank you,
Khoa

**Comment by qaschris** [comment]
I agree on all of these counts, to include the pulse-community repo as well.  The incoming/outgoing payload format/example may be extremely large, though.  Thoughts, Elise @femdev ?

However, to your final point about the console.log() for debugging, we will require a larger snapshot of the console log in Pulse itself in order to facilitate debugging, unless we ship everything to Slack, but Slack has a tendency to process webhooks out of order under load.  As of now, there's a hard character cutoff for the console log:
![image](https://user-images.githubusercontent.com/40035198/64640173-6e17e580-d3d7-11e9-9989-b499cf032e0e.png)

Regards,
Chris
